### PR TITLE
Removed unused variables

### PR DESCRIPTION
**Pull request by danielroehrig**
I searched the templates for any usage of the "all_recipes" or the
"current_node" variable and did find nothing. Deleting them has no
noticeable effect.

### CODE REVIEW

**Comment by danielroehrig** [comment]
Sometimes, I stumble upon code that I simply don't understand. Maybe if we could have a slack channel or similar, we could talk about them instead of creating a gazillion pull requests. ;)

**Comment by mrzapp** [comment]
@danielroehrig There may still be leftover code examples from the app tutorial, or from previous stuctural design irerations. 

I've created a matrix.org channel here: https://matrix.to/#/#nextcloud-cookbook:matrix.org

**Comment by danielroehrig** [comment]
Cool. My username is danielroehrig and the room seems to be invite only. Can you make the room public or send me an invite?

**Comment by mrzapp** [comment]
@danielroehrig the room is public, but I invited you anyway :)

**Pull request merged**
