### PR TITLE
Router rewrite

### PR DESCRIPTION
**Pull request by mcorteel**
This work is very much in progress, but I wanted to push something to start  a discussion!

What was done:
- [x] Simplify routing:
  - `/cookbook#some/route` calls `/cookbook/some/route` and renders the response in the content wrapper
  - POST and PUT requests are sent to the current route (`POST /cookbook/{id}/edit` for `/cookbook#{id}/edit`)
- [x] Create new routes
  - Search (to display results from the search bar
  - Tag (to display all recipes in a tag)
  - All (to display all recipes)
  - Category (to display a category) (for later, see last point)

The main change is that the nextcloud app doesn't directly use the API anymore. My plan would be to move the API to a new set of routes (probably with a prefix) for external applications.

What remains to be done:
- [ ] Create new routes for the API (@mrzapp I'm not sure if the  API is actually used for now, but I would suggest that we put it behind a `/cookbook/api` prefix to separate it from the actual nextcloud app)
- [x] Reimplement all previous functionality using this new routing paradigm
  -  Recipe import (I would like to include that in the "Create recipe" page to remove clutter from the navigation)
  - Settings
  - Other things that I forgot
- [ ] Reimplement the page-specific JS in some way (like collections of input)
- [ ] Do the work on categories. For now, the navigation shows tags as an alternative, but like @mrzapp mentioned, real categories  would make more sense in the long term. This will probably be another pull request, though.

Comments are very welcome!

### CODE REVIEW

**Comment by mcorteel** [comment]
OK, this is pretty much a complete proposal now! @mrzapp Looking forward to your suggestions :slightly_smiling_face:

**Comment by mcorteel** [comment]
Note: This also fixes #142.

**Comment by mrzapp** [comment]
@mcorteel Sorry, I've been super swamped with work the past month, but it's starting to clear up. These changes are truly phenomenal looking. Awesome work, sir!

About the feedback you requested:
- I agree that the API routes should be moved to `/cookbook/api`, is that the case in this complete pull request?
- Is there anything standing in the way of implementing the new categories? I really think the tags can just be used for the search index, or maybe a little tag cloud below the search box, if we want to get fancy.

**Comment by mrzapp** [comment]
@mcorteel I've merged the changes into 0.6.0, in case that wasn't clear, BTW.

**Comment by mcorteel** [comment]
* Yes, the routes have been moved to `/cookbook/api`
* I think categories should be pretty easy, but I haven't gotten to change anything in the database until now, so I will have to look into that.

**Comment by mrzapp** [comment]
@mcorteel nice.

I've cleaned up a bunch and polished some of the UI changes, please pull the latest from 0.6.0 to see them.

There were a few regressions, such as the "import" not working since it was made into a generalised "submitForm" handler, so I had to roll that change back. I do like it better when I can tell just by the function name exactly what it does anyway, so I'd prefer to keep it like that, if you don't mind.

The timer was a stroke of genius, BTW. I've improved it to include seconds for the sake of visual feedback.

**Pull request merged**
