### PR TITLE
Added "Uncategorized" Category

### PR DESCRIPTION
**Pull request by Teifun2**
All Recipes without a single keyword are grouped under the "Uncategorized" word, as requested in #110.

The category is currently called "Uncategorized". Many Dictionaries seem to have a problem with this word although i could not find a clear indication that it does not exists / is not correct. Maybe we could think of changing it to something different?

I could add German Translation here as well.

### CODE REVIEW

**Comment by mrzapp** [comment]
I think we just need to add the translation ourselves as you said.

Your approach is very respectful of the existing design pattern, I appreciate it 😊

I'll just go ahead and make you a collaborator, so you can push directly to `develop`, if you're making changes that don't require review.

**Comment by Teifun2** [comment]
Thank you very much. 
But how do i know the changes that i make don't need a review? :D

**Comment by mrzapp** [comment]
@Teifun2 that's mainly up to your personal judgement, as making you a collaborator places you within the circle of trust.

I would say that a bugfix or a minor enhancement usually doesn't need review, but a new feature usually does.

It can also just be if you would like feedback on your work for no particular reason :)

**Comment by Teifun2** [comment]
@mrzapp Ok i see. Thank you for that trust!

**Pull request merged**
